<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "tcaorder"
 *
 * Auto generated by Extension Builder 2019-08-25
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Respect sorting from Selectbox',
    'description' => 'Demo-Extension how to keep sort order from a Backend-Selectbox (aka selectMultipleSideBySide) without mm-Table.',
    'category' => 'plugin',
    'author' => 'Philipp Huberty',
    'author_email' => 'github@smartthings.de',
    'state' => 'alpha',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '9.5.0-9.5.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
